data_path_image: "/home/smslab1/PycharmProjects/AnomalyDetection/MMAD-main/dataset/MMAD/MVTec-AD"
backbone_names: [wideresnet50]
imagesize: 224
resize: 256
batch_size: 2
num_workers: 4
faiss_on_gpu: true
faiss_num_workers: 8
pretrain_embed_dimension: 1024
target_embed_dimension: 1024

model_path: "/home/smslab1/.cache/huggingface/hub/models--Qwen--Qwen2.5-VL-7B-Instruct/snapshots/cc594898137f460bfe9f0759e9844b3ce807cfb5"
model_name: qwen

dataset_name: DS-MVTec
domain_knowledge: true
threshold_method: k-sigma

reproduce: true
status: true
